#pragma once
#ifndef PICOMAMBA_PICOMAMBA_CONFIG_HPP
#define PICOMAMBA_PICOMAMBA_CONFIG_HPP

#define PICOMAMBA_VERSION_PATCH 0
#define PICOMAMBA_VERSION_MINOR 4
#define PICOMAMBA_VERSION_MAJOR 0

namespace picomamba {


} // end namespace picomamba


#endif // PICOMAMBA_PICOMAMBA_CONFIG_HPP